### ISSUE TITLE
The value is reset to "" when using setState

### ISSUE THREAD

**Issue by pavelkuligin** [nobbynobbs/react-dadata-suggestions#12] opened 2018-04-11 08:48 UTC
Hi! Thanks for the great solution for support DaData in React.

But there is a problem with setState inside onSelect:
`
<DadataSuggestions
    token={ token }
    placeholder="Иванов Иван Иванович"
    service="fio"
    onSelect={ (suggestion) => {  this.setState({person: suggestion}) } }
/>`

When I select a suggestion, the value of input reset to "". What am I doing wrong?

**Comment by nobbynobbs** [comment] 2018-04-11 09:36
Hi! I'm not sure, but probably I work wrong with context in callback functions in my component. I'll think about this issue.

**Comment by pavelkuligin** [comment] 2018-04-11 09:39
I found workaround already :-)
`
<DadataSuggestions
     token={ token }
     placeholder="Иванов Иван Иванович"
     query={this.state.query}
     onChange={(query) => this.setState({query: query}) }
     service="fio"
     onSelect={ (suggestion) => { this.setState({person: suggestion} ) } }
/>
`

**Comment by nobbynobbs** [comment] 2018-04-11 18:58
so can i close the issue?

**Comment by pavelkuligin** [comment] 2018-04-11 19:52
I think yes

**Closed as completed** 2018-04-11 20:30 UTC

**Comment by SDKiller** [comment] 2019-03-19 04:48
I thimk this should be reopened.

**Comment by nobbynobbs** [comment] 2019-03-19 06:21
@SDKiller maybe. But could you explain why?

**Comment by SDKiller** [comment] 2019-03-19 06:40
Foe example, I have a priviously stored user address and open form for edit.

I cannot even initialize field (underlying text input) with value -
component does allow to set it via value.

The suggestion above with placeholder is tricky and actually is not
suitable.

вт, 19 мар. 2019 г., 9:21 Roman <notifications@github.com>:

**Comment by SDKiller** [comment] 2019-03-19 06:43
Hm, I think that issue with "value" is worth opening another issue.

вт, 19 мар. 2019 г., 9:21 Roman <notifications@github.com>:

**Comment by nobbynobbs** [comment] 2019-03-19 06:58
@SDKiller 

You could use `query` option to initialize query string, see Address example at https://codesandbox.io/s/p95804280q

I think it fits your case.

**Comment by SDKiller** [comment] 2019-03-19 07:34
Thanks for example, if I initialize it via query - I got not editable field, I'll try to find what I'm doing wrong.

**Comment by SDKiller** [comment] 2019-03-19 11:50
@nobbynobbs 
Could you please suggest, how `onSelect` to send one more query with `unrestricted_value` and `count` 1?
The problem is that suggestions are returned with empty `geo_lat` and `geo_lon`.

According to today's answer of dadata support:

```
Подсказки возвращают координаты после того, как человек выбрал конкретный адрес из списка.

В API это запрос с параметром count = 1. При этом текст запроса должен быть результатом одного из предыдущих запросов (значением поля unrestricted_value). Например:

{ "query": "г Москва, ул Сухонская, д 11", "count": 1 }

```

**Comment by nobbynobbs** [comment] 2019-03-19 12:05
@SDKiller I'm afraid react-dadata-suggestion can't do such query for you. You could make this query manually in onSelect callback with fetch-api or axios.

**Comment by SDKiller** [comment] 2019-03-19 12:11
Thanks

вт, 19 мар. 2019 г., 15:05 Roman <notifications@github.com>:

**Comment by nobbynobbs** [comment] 2019-03-19 12:13
Not at all
